services:
  app: 
    image: joanfont/grall-api
    build: .
    depends_on:
      - redis
    ports: 
      - 8080:80
    volumes:
      - ./:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port" , "80", "--reload"]

  redis:
    image: library/redis:7.0-alpine
